on:
  push:
    branches: [ main ]
    paths:
      - '**/*.swift'
      - '**/*.m'
      - '**/*.mm'
      - '**/*.h'
      - '**/*.pbxproj'
      - '**/*.xcworkspace'
      - '**/*.xcconfig'
      - '**/*.entitlements'
      - '**/*.plist'
      - '**/*.xcodeproj/**'
      - '**/*.xcassets/**'

  pull_request:
    paths:
      - '**/*.swift'
      - '**/*.m'
      - '**/*.mm'
      - '**/*.h'
      - '**/*.pbxproj'
      - '**/*.xcworkspace'
      - '**/*.xcconfig'
      - '**/*.entitlements'
      - '**/*.plist'
      - '**/*.xcodeproj/**'
      - '**/*.xcassets/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s /Applications/Xcode.app
      - run: chmod +x ./ipabuild.sh
      - run: ./ipabuild.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ipa-build
          path: '**/*.ipa'
